import 'package:shuffle_uikit/shuffle_uikit.dart';

final largeBanners = [
  GraphicsFoundation.instance.png.mockAdBanner1.path,
  GraphicsFoundation.instance.png.mockAdBanner2.path,
  GraphicsFoundation.instance.png.mockAdBanner3.path,
  GraphicsFoundation.instance.png.mockAdBanner4.path,
  GraphicsFoundation.instance.png.mockAdBanner5.path,
  GraphicsFoundation.instance.png.mockAdBanner6.path,
  GraphicsFoundation.instance.png.mockAdBanner7.path,
  GraphicsFoundation.instance.png.mockAdBanner8.path,
  GraphicsFoundation.instance.png.mockAdBanner9.path,
  GraphicsFoundation.instance.png.mockAdBanner10.path,
  GraphicsFoundation.instance.png.mockAdBanner14.path,
  GraphicsFoundation.instance.png.mockAdBanner15.path,
  GraphicsFoundation.instance.png.mockAdBanner16.path,
];
final mediumBanners = [
  GraphicsFoundation.instance.png.mockAdBanner1.path,
  GraphicsFoundation.instance.png.mockAdBanner2.path,
  GraphicsFoundation.instance.png.mockAdBanner3.path,
  GraphicsFoundation.instance.png.mockAdBanner4.path,
  GraphicsFoundation.instance.png.mockAdBanner5.path,
  GraphicsFoundation.instance.png.mockAdBanner6.path,
  GraphicsFoundation.instance.png.mockAdBanner7.path,
  GraphicsFoundation.instance.png.mockAdBanner8.path,
  GraphicsFoundation.instance.png.mockAdBanner9.path,
  GraphicsFoundation.instance.png.mockAdBanner10.path,
  GraphicsFoundation.instance.png.mockAdBanner11.path,
  GraphicsFoundation.instance.png.mockAdBanner14.path,
  GraphicsFoundation.instance.png.mockAdBanner15.path,
  GraphicsFoundation.instance.png.mockAdBanner16.path,
];
final smallBanners = [
  GraphicsFoundation.instance.png.mockAdBanner1.path,
  GraphicsFoundation.instance.png.mockAdBanner2.path,
  GraphicsFoundation.instance.png.mockAdBanner3.path,
  GraphicsFoundation.instance.png.mockAdBanner4.path,
  GraphicsFoundation.instance.png.mockAdBanner5.path,
  GraphicsFoundation.instance.png.mockAdBanner6.path,
  GraphicsFoundation.instance.png.mockAdBanner7.path,
  GraphicsFoundation.instance.png.mockAdBanner8.path,
  GraphicsFoundation.instance.png.mockAdBanner9.path,
  GraphicsFoundation.instance.png.mockAdBanner10.path,
  GraphicsFoundation.instance.png.mockAdBanner11.path,
  GraphicsFoundation.instance.png.mockAdBanner12.path,
  GraphicsFoundation.instance.png.mockAdBanner15.path,
  GraphicsFoundation.instance.png.mockAdBanner17.path,
];
