name: shuffle_components_kit
description: A shuffle components kit
version: 0.0.1
homepage: none
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  #main ui kit
  shuffle_uikit:
  #  path: ../shuffle_uikit
    git:
      url: https://github.com/shuffle-app/shuffle_ui_kit.git
      ref: master

  #tools for config workers
  json_annotation: ^4.9.0
  json_serializable: ^6.9.2

  #voice
  flutter_sound_record: ^3.3.2
  just_audio: ^0.9.21
  file_picker: ^9.0.1

  #for barcode generate
  barcode_widget: ^2.0.4

  #for scan barcode
  mobile_scanner: ^6.0.2

  #scroll controller 
  anchor_scroll_controller: ^0.4.4

  #configuration libs
  http: ^1.2.1
  path_provider: ^2.1.5

  #ui_helpers
  palette_generator: ^0.3.3+5
  mask_text_input_formatter: ^2.9.0
#  infinite_scroll_pagination: ^4.0.0-dev.1
  duration: ^4.0.3
  bubble_lens:
#    path: ../bubble_lens
    git:
      url: https://github.com/shuffle-app/bubble_lens.git
      ref: main

  flutter_mobx: ^2.3.0
  visibility_detector: ^0.4.0+2
  

dependency_overrides:
  intl: ^0.20.0
  file: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
#  dart_code_metrics: ^5.7.3
  build_runner: ^2.4.14

#  dart_code_linter:
#    git:
#      url: https://github.com/shuffle-app/dart-code-linter.git
#      ref: trunk

flutter:

  uses-material-design: true

  assets:
    - assets/